### ISSUE TITLE
no HTML autocomplete or snippets in .astro files

### ISSUE THREAD

**Issue by PierBover** [SublimeText/Astro#10]
Just installed this extension in a mostly naked ST install (4180).

I'm trying to create a link and it's like it doesn't even recognize the HTML context.

<img width="711" alt="image" src="https://github.com/user-attachments/assets/4a77e421-2320-4b77-8202-93650fa32335">

The language is correctly selected as I can see `HTML (Astro)` in the bottom right:

<img width="608" alt="image" src="https://github.com/user-attachments/assets/870923ad-ac8d-45db-9276-3740e013e54a">

**Comment by deathaxe** [comment]
Astro files are (and need to be) scoped `source.astro` for astro language server to detect and handle them correctly.

`text.html.astro` was is added to also enable ST's HTML specific features (completions and snippets).

Please note: To enable auto completions changes of https://github.com/sublimehq/Packages/pull/4085 are required, because HTML's current `default_completions_selector` excludes all sorts of `source` scope.

You can wait for a ST release, which ships this change or manually apply required change to user specific HTML.sublime-settings.

**Comment by PierBover** [comment]
Thanks!

**Comment by PierBover** [comment]
Sorry to bother again but I can't figure it out.

I found some comments of yours on the forum saying this is needed to add the `source` scope in the `HTML.sublime-settings`:

```
{
    "default_completions_selector": "text.html - source - string"
}
```

But I'm still not getting any HTML completions in the the `.astro` files.

**Comment by deathaxe** [comment]
This old suggestion doesn't take into account html being embedded into `source` or even being scoped `source` as in case of Astro.

The reason it doesn't work is `- source`, which excludes `source.astro` as well.

As of Astro 2.10.0, defaults from mentioned PR would work as they only exclude `- text.html source`, which matches CSS/JS script tags only.

```jsonc
    "default_completions_selector": [
        // Plain HTML
        "text.html - text.html meta.embedded - text.html meta.interpolation - text.html source - (text.html.markdown - markup.raw.code-fence text.html), ",
        // Embedded HTML blocks
        "text.html.embedded - text.html.embedded meta.embedded - text.html.embedded meta.interpolation - text.html.embedded source",
    ]
```

**Comment by PierBover** [comment]
Thanks again!
