### ISSUE TITLE
Sublime's automatic indentation in frontmatter breaks page

### ISSUE THREAD

**Issue by deepspaceaxolotl** [SublimeText/Astro#6]
Not sure if this is something you can fix or not, it was already addressed [here](https://github.com/withastro/astro/issues/5285) and identified as an issue with YAML, but the issue I've run into is that Sublime auto indents the next line after a colon in the frontmatter with a tab instead of spaces like YAML expects. Could that be changed somehow? If not here, then does anyone know how? Having to remember to erase the auto indentation and replace it with four spaces manually is not ideal, but I don't want to give up on auto indentation entirely.

Example from Astro's tutorial:
working code:
```jsx
image:
    url: "https://docs.astro.build/assets/full-logo-light.png"
    alt: "The full Astro logo."
```
non-working code with Sublime's auto indentation:
```
image:
	url: "https://docs.astro.build/assets/full-logo-light.png"
	alt: "The full Astro logo."
```

**Comment by deathaxe** [comment]
You could set indentation style to 4 spaces for astro related files, but beyound that there's little to no chance to enforce certain indentation styles to parts of a document.

Even though YAML syntax is embedded into frontmatter, ST always applies settings of the main file's syntax everywhere.

The related core issue is: https://github.com/sublimehq/sublime_text/issues/5748

---

The only option I see is to ship a custom key binding for <kbd>tab</kbd> key which adds 4 spaces when called at the beginning of a line instead of `indent`. I'd look into it to find possible side-effects or edge cases.

That said, the default indentation level for YAML is 2 chars.

**Comment by deepspaceaxolotl** [comment]
Thanks for the suggestions! Hope there's some clever solution possible (I assume if the code block thing worked, we could have it recognise the --- fences as containing YAML and behave differently? hmm).

**Comment by deathaxe** [comment]
FWIW, Astro's HTML syntax uses TypeScript to highlight frontmatter.
